version: '3.8'

services:
  web:
    build: ./epoqueart
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./epoqueart/:/usr/src/epoqueart/
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data: