# Generated by Django 4.0.1 on 2022-01-28 14:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to=accounts.models.wrapper, verbose_name='avatar'),
        ),
    ]
