# Generated by Django 4.0.1 on 2022-03-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_painter',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(default='User', max_length=255, verbose_name='job'),
        ),
    ]
