# Generated by Django 4.0.1 on 2022-04-03 19:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_painter_alter_customuser_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='job',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Owner'), (2, 'Admin'), (3, 'Employee'), (4, 'User'), (5, 'Not Active')], default=4, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to=accounts.models.wrapper, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
