# Generated by Django 4.0.1 on 2022-04-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_job_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Administrative', (('Owner', 'Owner'), ('Administrator', 'Administrator'), ('Employee', 'Employee'))), ('Non-Administrative', (('User', 'User'), ('Not Active', 'Not Active')))], default='User', max_length=64, verbose_name='Role'),
        ),
    ]
