# Generated by Django 4.0.1 on 2022-04-04 09:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=accounts.models.wrapper, verbose_name='Avatar'),
        ),
    ]
