# Generated by Django 4.0.1 on 2022-01-30 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.wrapper, verbose_name='Painting')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_offline_available', models.BooleanField(verbose_name='Available in offline store?')),
                ('is_nft', models.BooleanField(verbose_name='Has NFT?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author account')),
            ],
        ),
    ]
