# Generated by Django 4.0.1 on 2022-03-31 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_preview', models.ImageField(help_text='This image will be shown at artists preview page.', upload_to=main.models.wrapper, verbose_name='Artist preview photo')),
                ('artist_photo', models.ImageField(help_text='This image will be shown at artist page.', upload_to=main.models.wrapper, verbose_name='Artist photo')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('qualification', models.CharField(help_text="Qualification of artist, e.g. 'Surrealist master'", max_length=255, verbose_name='Qualification')),
                ('biography', models.TextField(verbose_name='Biography')),
            ],
            options={
                'verbose_name': 'Painting',
                'verbose_name_plural': 'Paintings',
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Painting', max_length=512, verbose_name='Picture name')),
                ('image', models.ImageField(upload_to=main.models.wrapper, verbose_name='Painting')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(default=0, verbose_name='Price ($)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('width', models.PositiveIntegerField(default=0, help_text='Determines width of painting', verbose_name='Width')),
                ('height', models.PositiveIntegerField(default=0, help_text='Determines height of painting', verbose_name='Height')),
                ('measure', models.PositiveIntegerField(choices=[(1, 'Inch'), (2, 'Centimeter')], default=1, verbose_name='Measure unit')),
                ('is_offline_available', models.BooleanField(default=False, help_text='Determines if there is a painting in the store at the moment.', verbose_name='Availability in the offline store')),
                ('nft', models.CharField(blank=True, help_text='Link to an NFT project, if no NFT leave blank.', max_length=1024, null=True, unique=True, verbose_name='NFT')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artist', verbose_name='Author account')),
            ],
            options={
                'verbose_name': 'Painting',
                'verbose_name_plural': 'Paintings',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of post', max_length=150, verbose_name='Title')),
                ('date', models.DateField(help_text='Date of event', verbose_name='Date')),
                ('content', models.TextField(help_text='Description', verbose_name='Content')),
                ('image', models.ImageField(upload_to=main.models.wrapper, verbose_name='Painting')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author account')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-date'],
            },
        ),
    ]
