# Generated by Django 4.0.1 on 2022-01-30 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='name',
            field=models.CharField(default='Unnamed Painting', max_length=512, verbose_name='Picture name'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='is_nft',
            field=models.BooleanField(default=False, verbose_name='Has NFT?'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='is_offline_available',
            field=models.BooleanField(default=False, verbose_name='Available in offline store?'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price ($)'),
        ),
    ]
