# Generated by Django 4.0.1 on 2022-04-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_artwork_artwork_status_artwork_type_author_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork_status',
            options={'verbose_name': 'Artwork Status', 'verbose_name_plural': 'Artwork Status'},
        ),
        migrations.AlterModelOptions(
            name='artwork_type',
            options={'verbose_name': 'Artwork Type', 'verbose_name_plural': 'Artwork Type'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='lname',
        ),
    ]
