# Generated by Django 4.0.1 on 2022-04-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_artwork_status_artwork_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date',
            field=models.DateField(help_text='Date of creation of artwork.', null=True, verbose_name='Date'),
        ),
    ]
