# Generated by Django 4.0.1 on 2022-04-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_artwork_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'verbose_name': 'Artwork', 'verbose_name_plural': 'Artworks'},
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
