# Generated by Django 4.0.1 on 2022-04-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_artwork_options_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
