# Generated by Django 4.0.1 on 2022-04-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(help_text='Name of event.', max_length=255, unique=True, verbose_name='Title'),
        ),
    ]
