# Generated by Django 4.0.1 on 2022-04-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_event_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='author',
            field=models.ForeignKey(help_text='Author of artwork.', on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='main.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='measure',
            field=models.CharField(choices=[('Inch', 'Inch'), ('Centimeters', 'Centimeters')], max_length=24, verbose_name='Measure unit'),
        ),
    ]
